[package]
name = "input-capture"
description = "cross-platform input-capture library used by lan-mouse"
version = "0.4.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures = { workspace = true }
futures-core = { workspace = true }
log = { workspace = true }
input-event = { workspace = true }
memmap = "0.7"
tempfile = "3.25.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "process",
    "rt",
    "sync",
    "signal",
    "time",
] }
once_cell = { workspace = true }
async-trait = { workspace = true }
tokio-util = { workspace = true }

[target.'cfg(all(unix, not(target_os="macos")))'.dependencies]
wayland-client = { workspace = true, optional = true }
wayland-protocols = { workspace = true, features = [
    "client",
    "staging",
    "unstable",
], optional = true }
wayland-protocols-wlr = { workspace = true, features = [
    "client",
], optional = true }
x11 = { workspace = true, optional = true }
ashpd = { workspace = true, features = [
    "input_capture",
    "tokio",
], optional = true }
reis = { workspace = true, features = ["tokio"], optional = true }

[target.'cfg(target_os="macos")'.dependencies]
core-graphics = { workspace = true }
core-foundation = { workspace = true }
core-foundation-sys = { workspace = true }
libc = { workspace = true }
keycode = { workspace = true }
bitflags = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Graphics",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
default = ["layer_shell", "x11", "libei"]
metrics = []
layer_shell = [
    "dep:wayland-client",
    "dep:wayland-protocols",
    "dep:wayland-protocols-wlr",
]
x11 = ["dep:x11"]
libei = ["dep:reis", "dep:ashpd"]
