name: "Release"
run-name: "Release - ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.event.inputs.name || github.ref_name }}"

on:
  push:
    branches: [ "main" ]
    tags:
      - v**
  workflow_dispatch:
    inputs:
      name:
        description: 'Development release name'
        required: false
        default: ''

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-release-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxtst-dev
    - name: Release Build
      run: |
        cargo build --release --bins
        cp target/release/crossdesk CrossDesk-linux-x86_64
        cp target/release/lan-mouse lan-mouse-cli-linux-x86_64
    - name: Install cargo bundle
      run: cargo install cargo-bundle
    - name: Bundle
      run: |
        cargo bundle --release --bin crossdesk
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: crossdesk-linux-x86_64
        path: |
          CrossDesk-linux-x86_64
          lan-mouse-cli-linux-x86_64
          target/release/bundle/deb/crossdesk_*.deb
          target/release/bundle/appimage/crossdesk_*.AppImage

  linux-arm64-release-build:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v6
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxtst-dev
    - name: Release Build
      run: |
        cargo build --release --bins
        cp target/release/crossdesk CrossDesk-linux-arm64
        cp target/release/lan-mouse lan-mouse-cli-linux-arm64
    - name: Install cargo bundle
      run: cargo install cargo-bundle
    - name: Bundle
      run: |
        cargo bundle --release --bin crossdesk
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: crossdesk-linux-arm64
        path: |
          CrossDesk-linux-arm64
          lan-mouse-cli-linux-arm64
          target/release/bundle/deb/crossdesk_*.deb
          target/release/bundle/appimage/crossdesk_*.AppImage

  windows-release-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Release Build
      run: cargo build --release --bins
    - name: Create Archive
      run: |
        mkdir "crossdesk-windows"
        Copy-Item -Path "target\release\crossdesk.exe" -Destination "crossdesk-windows\CrossDesk.exe"
        Copy-Item -Path "target\release\lan-mouse.exe" -Destination "crossdesk-windows\lan-mouse.exe"
        Compress-Archive -Path "crossdesk-windows\*" -DestinationPath crossdesk-windows-x86_64.zip
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: crossdesk-windows-x86_64
        path: crossdesk-windows-x86_64.zip

  macos-release-build:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v6
    - name: install dependencies
      run: |
        brew install imagemagick librsvg
    - name: Release Build
      run: |
        cargo build --release --bins
    - name: Make icns
      run: scripts/makeicns.sh
    - name: Install cargo bundle
      run: cargo install cargo-bundle
    - name: Bundle
      run: |
        cargo bundle --release --bin crossdesk
    - name: Zip bundle
      run: |
        cd target/release/bundle/osx
        zip -r "crossdesk-macos-intel.zip" "CrossDesk.app"
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: crossdesk-macos-intel
        path: target/release/bundle/osx/crossdesk-macos-intel.zip

  macos-arm64-release-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v6
    - name: install dependencies
      run: |
        brew install imagemagick librsvg
    - name: Release Build
      run: |
        cargo build --release --bins
    - name: Make icns
      run: scripts/makeicns.sh
    - name: Install cargo bundle
      run: cargo install cargo-bundle
    - name: Bundle
      run: |
        cargo bundle --release --bin crossdesk
    - name: Zip bundle
      run: |
        cd target/release/bundle/osx
        zip -r "crossdesk-macos-arm64.zip" "CrossDesk.app"
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: crossdesk-macos-arm64
        path: target/release/bundle/osx/crossdesk-macos-arm64.zip

  release:
    name: "Release"
    needs: [windows-release-build, linux-release-build, linux-arm64-release-build, macos-release-build, macos-arm64-release-build]
    runs-on: "ubuntu-latest"
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
    - name: Get short SHA
      id: vars
      run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
    - name: Create Pre-Release
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ format('{0}-{1}', github.event.inputs.name || github.ref_name, steps.vars.outputs.short_sha) }}
        name: ${{ format('{0}-{1}', github.event.inputs.name || github.ref_name, steps.vars.outputs.short_sha) }}
        prerelease: true
        generate_release_notes: true
        files: |
          crossdesk-linux-x86_64/CrossDesk-linux-x86_64
          crossdesk-linux-x86_64/lan-mouse-cli-linux-x86_64
          crossdesk-linux-x86_64/target/release/bundle/deb/crossdesk_*.deb
          crossdesk-linux-x86_64/target/release/bundle/appimage/crossdesk_*.AppImage
          crossdesk-linux-arm64/CrossDesk-linux-arm64
          crossdesk-linux-arm64/lan-mouse-cli-linux-arm64
          crossdesk-linux-arm64/target/release/bundle/deb/crossdesk_*.deb
          crossdesk-linux-arm64/target/release/bundle/appimage/crossdesk_*.AppImage
          crossdesk-macos-intel/crossdesk-macos-intel.zip
          crossdesk-macos-arm64/crossdesk-macos-arm64.zip
          crossdesk-windows-x86_64/crossdesk-windows-x86_64.zip
    - name: Create Tagged Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: |
          crossdesk-linux-x86_64/CrossDesk-linux-x86_64
          crossdesk-linux-x86_64/lan-mouse-cli-linux-x86_64
          crossdesk-linux-x86_64/target/release/bundle/deb/crossdesk_*.deb
          crossdesk-linux-x86_64/target/release/bundle/appimage/crossdesk_*.AppImage
          crossdesk-linux-arm64/CrossDesk-linux-arm64
          crossdesk-linux-arm64/lan-mouse-cli-linux-arm64
          crossdesk-linux-arm64/target/release/bundle/deb/crossdesk_*.deb
          crossdesk-linux-arm64/target/release/bundle/appimage/crossdesk_*.AppImage
          crossdesk-macos-intel/crossdesk-macos-intel.zip
          crossdesk-macos-arm64/crossdesk-macos-arm64.zip
          crossdesk-windows-x86_64/crossdesk-windows-x86_64.zip
