[package]
name = "input-emulation"
description = "cross-platform input emulation library used by lan-mouse"
version = "0.4.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
input-event = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "process",
    "rt",
    "sync",
    "signal",
    "time",
] }
once_cell = { workspace = true }

[target.'cfg(all(unix, not(target_os="macos")))'.dependencies]
bitflags = { workspace = true }
wayland-client = { workspace = true, optional = true }
wayland-protocols = { workspace = true, features = [
    "client",
    "staging",
    "unstable",
], optional = true }
wayland-protocols-wlr = { workspace = true, features = [
    "client",
], optional = true }
wayland-protocols-misc = { workspace = true, features = [
    "client",
], optional = true }
x11 = { workspace = true, optional = true }
ashpd = { workspace = true, features = [
    "remote_desktop",
    "screencast",
    "tokio",
], optional = true }
reis = { workspace = true, features = ["tokio"], optional = true }

[target.'cfg(target_os="macos")'.dependencies]
bitflags = { workspace = true }
core-foundation = { workspace = true }
core-foundation-sys = { workspace = true }
core-graphics = { workspace = true }
keycode = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Graphics",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
default = ["wlroots", "x11", "remote_desktop_portal", "libei"]
wlroots = [
    "dep:wayland-client",
    "dep:wayland-protocols",
    "dep:wayland-protocols-wlr",
    "dep:wayland-protocols-misc",
]
x11 = ["dep:x11"]
remote_desktop_portal = ["dep:ashpd"]
libei = ["dep:reis", "dep:ashpd"]
